"""
Deterministic demo/prototype scenario definitions.

Every number the analysis services produce is computed from the synthetic raster
arrays generated by generate_imagery.py using these configs as the "ground truth"
layout -- nothing downstream is a hardcoded literal. Regions are fictional/synthetic
demo AOIs (not real survey data), clearly labeled DEMO/PROTOTYPE throughout the UI.
"""

from datetime import datetime, timezone

IMG_SIZE = 512

REGIONS: dict[str, dict] = {
    "aoi-riverside-corridor": {
        "label": "Demo AOI — Riverside Corridor (Synthetic)",
        "description": "Peri-urban corridor along a river, used for bi-temporal built-up change demo.",
        # fictional bounding box, EPSG:4326, ~5km x 5km
        "bbox": [78.401, 17.352, 78.451, 17.402],
        "modes": ["bi_temporal"],
    },
    "aoi-coastal-wetland": {
        "label": "Demo AOI — Coastal Wetland Margin (Synthetic)",
        "description": "Wetland margin used for optical+SAR cross-modal demo and cross-domain correlation.",
        "bbox": [83.201, 19.802, 83.251, 19.852],
        "modes": ["optical_sar"],
    },
    "aoi-agro-mosaic": {
        "label": "Demo AOI — Agricultural Mosaic (Synthetic)",
        "description": "Mixed agricultural landscape used for single-image VQA/captioning/grounding demo.",
        "bbox": [77.101, 15.602, 77.151, 15.652],
        "modes": ["single_image"],
    },
}

# ---------------------------------------------------------------------------
# Bi-temporal urban expansion (optical, T1 -> T2)
# ---------------------------------------------------------------------------
BI_TEMPORAL = {
    "region_key": "aoi-riverside-corridor",
    "t1": {
        "acquisition_time": datetime(2023, 1, 15, 5, 12, tzinfo=timezone.utc),
        "sensor_type": "optical",
        "modality": "multispectral (R,G,B,NIR)",
        "crs": "EPSG:4326",
        "resolution_m": 10.0,
        "bands": ["Red", "Green", "Blue", "NIR"],
        "image_file": "riverside_t1.png",
        "name": "Riverside Corridor — Optical T1",
    },
    "t2": {
        "acquisition_time": datetime(2025, 6, 20, 5, 9, tzinfo=timezone.utc),
        "sensor_type": "optical",
        "modality": "multispectral (R,G,B,NIR)",
        "crs": "EPSG:4326",
        "resolution_m": 10.0,
        "bands": ["Red", "Green", "Blue", "NIR"],
        "image_file": "riverside_t2.png",
        "name": "Riverside Corridor — Optical T2",
    },
    # generator layout: seed geometry for built-up seed clusters, river band, growth clusters
    "layout": {
        "river": {"x0": 0, "x1": 70, "wobble": 14},
        "vegetation_seed": 7,
        "settlement_t1": [
            {"cx": 150, "cy": 340, "r": 46},
            {"cx": 190, "cy": 300, "r": 30},
        ],
        "settlement_growth_t2": [
            {"cx": 230, "cy": 330, "r": 58},
            {"cx": 150, "cy": 400, "r": 40},
            {"cx": 300, "cy": 280, "r": 34},
        ],
        "road_t2": {"y": 360, "thickness": 6},
    },
}

# ---------------------------------------------------------------------------
# Optical + SAR cross-modal (single time, two sensors, same footprint)
# ---------------------------------------------------------------------------
OPTICAL_SAR = {
    "region_key": "aoi-coastal-wetland",
    "optical": {
        "acquisition_time": datetime(2024, 11, 3, 5, 30, tzinfo=timezone.utc),
        "sensor_type": "optical",
        "modality": "multispectral (R,G,B,NIR)",
        "crs": "EPSG:4326",
        "resolution_m": 10.0,
        "bands": ["Red", "Green", "Blue", "NIR"],
        "image_file": "wetland_optical.png",
        "name": "Coastal Wetland — Optical",
    },
    "sar": {
        "acquisition_time": datetime(2024, 11, 4, 23, 51, tzinfo=timezone.utc),
        "sensor_type": "sar",
        "modality": "C-band SAR (VV)",
        "crs": "EPSG:4326",
        "resolution_m": 10.0,
        "bands": ["VV"],
        "image_file": "wetland_sar.png",
        "name": "Coastal Wetland — SAR (VV)",
    },
    "layout": {
        "true_water": {"cx": 260, "cy": 260, "r": 90},
        # a patch that looks water-like optically (damp soil / specular sheen) but is NOT
        # confirmed as water by SAR backscatter -- the deliberate cross-sensor conflict
        "ambiguous_patch": {"cx": 400, "cy": 140, "r": 42},
        "vegetation_seed": 11,
    },
}

# ---------------------------------------------------------------------------
# Single image (VQA / captioning / grounding)
# ---------------------------------------------------------------------------
SINGLE_IMAGE = {
    "region_key": "aoi-agro-mosaic",
    "observation": {
        "acquisition_time": datetime(2024, 3, 8, 5, 20, tzinfo=timezone.utc),
        "sensor_type": "optical",
        "modality": "multispectral (R,G,B,NIR)",
        "crs": "EPSG:4326",
        "resolution_m": 10.0,
        "bands": ["Red", "Green", "Blue", "NIR"],
        "image_file": "agro_single.png",
        "name": "Agricultural Mosaic — Optical",
    },
    "layout": {
        "pond": {"cx": 120, "cy": 400, "r": 38},
        "settlement": {"cx": 420, "cy": 90, "r": 44},
        "road_y": 250,
        "field_seed": 21,
    },
}

# ---------------------------------------------------------------------------
# External environmental signal for cross-domain correlation (Innovation 2)
# tied to aoi-coastal-wetland, deliberately correlated with the water-extent
# change region computed from OPTICAL_SAR at analysis time.
# ---------------------------------------------------------------------------
EXTERNAL_SIGNAL = {
    "region_key": "aoi-coastal-wetland",
    "source": "Community wading-bird occurrence log (synthetic demo dataset)",
    "signal_type": "species_occurrence_count",
    "unit": "individuals observed / survey",
    "points": [
        # (days_offset_from_2024-09-01, value, near_geometry)
        (0, 12, {"cx": 400, "cy": 140}),
        (14, 15, {"cx": 400, "cy": 140}),
        (30, 19, {"cx": 400, "cy": 140}),
        (45, 26, {"cx": 400, "cy": 140}),
        (60, 31, {"cx": 400, "cy": 140}),
        (64, 33, {"cx": 260, "cy": 260}),
    ],
}
